// Generated by gencs from human_navigation/HumanNaviTaskInfo.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

namespace SIGVerse.RosBridge
{
	namespace human_navigation
	{
		[System.Serializable]
		public class HumanNaviTaskInfo : RosMessage
		{
			public string environment_id;
			public human_navigation.HumanNaviObjectInfo target_object;
			public human_navigation.HumanNaviDestination destination;
			public System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo> non_target_objects;
			public System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo> furniture;

			public HumanNaviTaskInfo()
			{
				environment_id = "";
				target_object = new human_navigation.HumanNaviObjectInfo();
				destination = new human_navigation.HumanNaviDestination();
				non_target_objects = new System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo>();
				furniture = new System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo>();
			}

			public HumanNaviTaskInfo(string _environment_id, human_navigation.HumanNaviObjectInfo _target_object, human_navigation.HumanNaviDestination _destination, System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo> _non_target_objects, System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo> _furniture)
			{
				environment_id = _environment_id;
				target_object = _target_object;
				destination = _destination;
				non_target_objects = _non_target_objects;
				furniture = _furniture;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviTaskInfo";
			}

			new public static string GetMD5Hash()
			{
				return "72a83c8dcb8252f4b5e97040679254a7";
			}

		} // class HumanNaviTaskInfo
	} // namespace human_navigation
} // namespace ROSBridgeLib