// Generated by gencs from human_navigation/HumanNaviObjectInfo.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

namespace SIGVerse.RosBridge
{
	namespace human_navigation
	{
		[System.Serializable]
		public class HumanNaviObjectInfo : RosMessage
		{
			public string name;
			public UnityEngine.Vector3 position;


			public HumanNaviObjectInfo()
			{
				name = "";
				position = new UnityEngine.Vector3();

			}

			public HumanNaviObjectInfo(string _name, UnityEngine.Vector3 _position)
			{
				name = _name;
				position = _position;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviObjectInfo";
			}

			new public static string GetMD5Hash()
			{
				return "899cf99e2e01a64170a87c0171b5b2ec";
			}

		} // class HumanNaviObjectInfo

	} // namespace human_navigation

} // namespace ROSBridgeLib