// Generated by gencs from human_navigation/HumanNaviMsg.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

namespace SIGVerse.RosBridge
{
	namespace human_navigation
	{
		[System.Serializable]
		public class HumanNaviMsg : RosMessage
		{
			public string message;
			public string detail;

			public HumanNaviMsg()
			{
				this.message = "";
				this.detail = "";
			}

			public HumanNaviMsg(string message, string detail)
			{
				this.message = message;
				this.detail = detail;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviMsg";
			}

			new public static string GetMD5Hash()
			{
				return "83c3ad4b113aebdb7a85eba9ba595d50";
			}
		} // class HumanNaviMsg
	} // namespace human_navigation
} // namespace SIGVerse.RosBridge

