// Generated by gencs from human_navigation/HumanNaviObjectInfo.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

namespace SIGVerse.RosBridge
{
	namespace human_navigation
	{
		[System.Serializable]
		public class HumanNaviObjectInfo : RosMessage
		{
			public string name;
			public UnityEngine.Vector3 position;
			public UnityEngine.Quaternion orientation;

			public HumanNaviObjectInfo()
			{
				name = "";
				position = new UnityEngine.Vector3();
				orientation = new UnityEngine.Quaternion();

			}

			public HumanNaviObjectInfo(string _name, UnityEngine.Vector3 _position, UnityEngine.Quaternion _orientation)
			{
				name = _name;
				position = _position;
				orientation = _orientation;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviObjectInfo";
			}

			new public static string GetMD5Hash()
			{
				return "65b1250e41281e50a63b24196f1ad619";
			}

		} // class HumanNaviObjectInfo

	} // namespace human_navigation

} // namespace ROSBridgeLib