// Generated by gencs from human_navigation/HumanNaviTaskInfo.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

namespace SIGVerse.RosBridge
{
	namespace human_navigation
	{

		[System.Serializable]
		public class HumanNaviTaskInfo : RosMessage
		{
			public string environment_id;
			public System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo> objects_info;
			public human_navigation.HumanNaviObjectInfo target_object;
			public UnityEngine.Vector3 destination;

			public HumanNaviTaskInfo()
			{
				environment_id = "";
				objects_info = new System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo>();
				target_object = new human_navigation.HumanNaviObjectInfo();
				destination = new UnityEngine.Vector3();

			}

			public HumanNaviTaskInfo(string _environment_id, System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo> _objects_info, human_navigation.HumanNaviObjectInfo _target_object, UnityEngine.Vector3 _destination)
			{
				environment_id = _environment_id;
				objects_info = _objects_info;
				target_object = _target_object;
				destination = _destination;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviTaskInfo";
			}

			new public static string GetMD5Hash()
			{
				return "a171437ef155a1af48679c78f18cbc7d";
			}

		} // class HumanNaviTaskInfo

	} // namespace human_navigation

} // namespace ROSBridgeLib