// Generated by gencs from human_navigation/HumanNaviDestination.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

namespace SIGVerse.RosBridge
{
	namespace human_navigation
	{
		[System.Serializable]
		public class HumanNaviDestination : RosMessage
		{
			public UnityEngine.Vector3 position;
			public UnityEngine.Quaternion orientation;
			public UnityEngine.Vector3 size;


			public HumanNaviDestination()
			{
				position = new UnityEngine.Vector3();
				orientation = new UnityEngine.Quaternion();
				size = new UnityEngine.Vector3();

			}

			public HumanNaviDestination(UnityEngine.Vector3 _position, UnityEngine.Quaternion _orientation, UnityEngine.Vector3 _size)
			{
				position = _position;
				orientation = _orientation;
				size = _size;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviDestination";
			}

			new public static string GetMD5Hash()
			{
				return "e9adffd11b4bc3effe2908e9f95d5bea";
			}

		} // class HumanNaviDestination
	} // namespace human_navigation
} // namespace ROSBridgeLib
