// Generated by gencs from human_navigation/HumanNaviTaskInfo.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.ROSBridge;
using UnityEngine;

namespace SIGVerse.ROSBridge
{
	namespace human_navigation
	{
		[System.Serializable]
		public class HumanNaviAvatarPose : ROSMessage
		{
			public geometry_msgs.Pose head;
			public geometry_msgs.Pose left_hand;
			public geometry_msgs.Pose right_hand;

			public HumanNaviAvatarPose()
			{
				head = new geometry_msgs.Pose();
				left_hand = new geometry_msgs.Pose();
				right_hand = new geometry_msgs.Pose();
			}

			public HumanNaviAvatarPose(geometry_msgs.Pose _head, geometry_msgs.Pose _left_hand, geometry_msgs.Pose _right_hand)
			{
				head = _head;
				left_hand = _left_hand;
				right_hand = _right_hand;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviAvatarPose";
			}

			new public static string GetMD5Hash()
			{
				return "da17fe0a6c6bd33b9ccc614a3a7af77c";
			}

		} // class HumanNaviAvatarPose

	} // namespace human_navigation

} // namespace ROSBridgeLib