// Generated by gencs from human_navigation/HumanNaviGuidanceMsg.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace SIGVerse.RosBridge
{
	namespace human_navigation
	{
		[System.Serializable]
		public class HumanNaviGuidanceMsg : RosMessage
		{
			public string message;
			public string display_type;

			public HumanNaviGuidanceMsg()
			{
				message = "";
				display_type = "";
			}

			public HumanNaviGuidanceMsg(string _message, string _display_type)
			{
				message = _message;
				display_type = _display_type;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviGuidanceMsg";
			}

			new public static string GetMD5Hash()
			{
				return "61cc6c45b4669a8bb054d2fc90a5dff7";
			}

		} // class HumanNaviGuidanceMsg
	} // namespace human_navigation
} // namespace ROSBridgeLib
