// Generated by gencs from human_navigation/HumanNaviObjectStatus.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

namespace SIGVerse.RosBridge
{
	namespace human_navigation
	{
		[System.Serializable]
		public class HumanNaviObjectStatus : RosMessage
		{
			public human_navigation.HumanNaviObjectInfo target_object;
			public System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo> non_target_objects;

			public HumanNaviObjectStatus()
			{
				target_object = new human_navigation.HumanNaviObjectInfo();
				non_target_objects = new System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo>();
			}

			public HumanNaviObjectStatus(human_navigation.HumanNaviObjectInfo _target_object, System.Collections.Generic.List<human_navigation.HumanNaviObjectInfo> _non_target_objects)
			{
				target_object = _target_object;
				non_target_objects = _non_target_objects;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviObjectStatus";
			}

			new public static string GetMD5Hash()
			{
				return "dc923dcd95df576c03a3a3f61c038230";
			}
		} // class HumanNaviObjectStatus
	} // namespace human_navigation
} // namespace ROSBridgeLib
