// Generated by gencs from human_navigation/HumanNaviAvatarStatus.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;

namespace SIGVerse.RosBridge
{
	namespace human_navigation
	{
		[System.Serializable]
		public class HumanNaviAvatarStatus : RosMessage
		{
			public geometry_msgs.Pose head;
			public geometry_msgs.Pose body;
			public geometry_msgs.Pose left_hand;
			public geometry_msgs.Pose right_hand;
			public string object_in_left_hand;
			public string object_in_right_hand;
			public bool is_target_object_in_left_hand;
			public bool is_target_object_in_right_hand;


			public HumanNaviAvatarStatus()
			{
				head = new geometry_msgs.Pose();
				body = new geometry_msgs.Pose();
				left_hand = new geometry_msgs.Pose();
				right_hand = new geometry_msgs.Pose();
				object_in_left_hand = "";
				object_in_right_hand = "";
				is_target_object_in_left_hand = false;
				is_target_object_in_right_hand = false;

			}

			public HumanNaviAvatarStatus(geometry_msgs.Pose _head, geometry_msgs.Pose _body, geometry_msgs.Pose _left_hand, geometry_msgs.Pose _right_hand, string _object_in_left_hand, string _object_in_right_hand, bool _is_target_object_in_left_hand, bool _is_target_object_in_right_hand)
			{
				head = _head;
				body = _body;
				left_hand = _left_hand;
				right_hand = _right_hand;
				object_in_left_hand = _object_in_left_hand;
				object_in_right_hand = _object_in_right_hand;
				is_target_object_in_left_hand = _is_target_object_in_left_hand;
				is_target_object_in_right_hand = _is_target_object_in_right_hand;
			}

			new public static string GetMessageType()
			{
				return "human_navigation/HumanNaviAvatarStatus";
			}

			new public static string GetMD5Hash()
			{
				return "f9190ca25b6cd6192693cc3f2a3156de";
			}

		} // class HumanNaviAvatarStatus

	} // namespace human_navigation

} // namespace ROSBridgeLib
